### ISSUE TITLE
Error in `minitar.rb:78:in `open': uninitialized constant #<Class:Minitar>::Input (NameError)`

### ISSUE THREAD

**Issue by aramprice** [halostatue/minitar#58]
Reproduction on ruby 3.2.5 - freshly installed via `ruby-install`:
```
irb(main):001:0> require 'minitar'
=> true
irb(main):002:0> puts Minitar::VERSION
1.0.0
=> nil
irb(main):003:0> RUBY_VERSION
=> "3.2.5"
irb(main):004:0> Minitar.open('foo')
~/.gem/ruby/3.2.5/gems/minitar-1.0.0/lib/minitar.rb:78:in `open': uninitialized constant #<Class:Minitar>::Input (NameError)

      Input.open(dest, &)
      ^^^^^
	from (irb):2:in `<main>'
	from ~/.rubies/ruby-3.2.5/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from ~/.rubies/ruby-3.2.5/bin/irb:25:in `load'
	from ~/.rubies/ruby-3.2.5/bin/irb:25:in `<main>'
irb(main):005:0>
```

**Comment by aramprice** [comment]
I _think_ this is the needed fix:

```patch
diff --git a/lib/minitar.rb b/lib/minitar.rb
index 7ab1a57..910f4f4 100644
--- a/lib/minitar.rb
+++ b/lib/minitar.rb
@@ -75,9 +75,9 @@ class << Minitar
   def open(dest, mode = "r", &)
     case mode
     when "r"
-      Input.open(dest, &)
+      Minitar::Input.open(dest, &)
     when "w"
-      Output.open(dest, &block)
+      Minitar::Output.open(dest, &block)
     else
       raise "Unknown open mode for Minitar.open."
     end
```

**Comment by halostatue** [comment]
Thank you for the bug report and proposed fix.

**Comment by aramprice** [comment]
Thank you for the quick fix!
