### ISSUE TITLE
 LoadError when requiring archive/tar/minitar after recent version bump to 1.0.1

### ISSUE THREAD

**Issue by killbotXD** [halostatue/minitar#61]
After updating to the latest version of the minitar gem, I'm encountering a LoadError when trying to require archive/tar/minitar. This issue occurs in my project which relies on the berkshelf gem. The error seems to be related to the changes introduced in the recent version of minitar.

Error Message:
```
<internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require': cannot load such file -- archive/tar/minitar (LoadError)
	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/berkshelf-8.0.9/lib/berkshelf/packager.rb:1:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/berkshelf-8.0.9/lib/berkshelf/berksfile.rb:1:in `require_relative'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/berkshelf-8.0.9/lib/berkshelf/berksfile.rb:1:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/berkshelf-8.0.9/lib/berkshelf.rb:222:in `require_relative'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/berkshelf-8.0.9/lib/berkshelf.rb:222:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/berkshelf-8.0.9/lib/berkshelf/cli.rb:1:in `require_relative'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/berkshelf-8.0.9/lib/berkshelf/cli.rb:1:in `<top (required)>'
	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/berkshelf-8.0.9/bin/berks:3:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/bin/berks:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/bin/berks:25:in `<main>'

```

Steps to Reproduce:

Run a project that depends on berkshelf which internally requires archive/tar/minitar.
Observe the LoadError during runtime.
Expected Behavior:
The minitar gem should load successfully without raising a LoadError.

Environment:

Ruby version: 3.3.0
Library being used: Berkshelf 8.0.9
Gem version: minitar 1.0.1

Thank you for looking into this issue.

**Comment by halostatue** [comment]
This is an intentional breaking change. It has been documented for years that `archive/tar/minitar` is going away.

The last version that supports that namespace is 0.12, released the day before 1.0.
